global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:5000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:80']

  - job_name: 'user-profile-service'
    static_configs:
      - targets: ['user-profile-service:80']

  - job_name: 'cocktail-import-service'
    static_configs:
      - targets: ['cocktail-import-service:80']

  - job_name: 'cocktail-submission-service'
    static_configs:
      - targets: ['cocktail-submission-service:80']

  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']