global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'dotnet-apps'
    static_configs:
      - targets:
          - auth-service:80
          - user-profile-service:80
          - cocktail-import-service:80
          - cocktail-service:80
          - search-service:80
